buildings:
  BuildingA: ["1:00-1:25", "1:30-1:55", "2:00-2:25", "2:30-2:55", "3:00-3:25"]
  BuildingB: ["1:30-1:55", "2:00-2:25", "2:30-2:55", "3:00-3:25", "3:30-3:55"]
building_order: ["BuildingA", "BuildingB"]
movement:
  policy: none
  phase_slot:
    BuildingA: 2
    BuildingB: 1
breaks: [3]

areas: ["Area1", "Area2"]
area_weights:
  Area1: 1.0
  Area2: 0.5

faculty_availability:
  Faculty A: [2, 3, 4, 5]
  Faculty B: [1, 2, 3, 4, 5]
  Faculty C: [1, 2, 3]
  Faculty D: []
