buildings:
  ABC: ["1:00-1:25", "1:30-1:55", "2:00-2:25", "2:30-2:55"]
  XYZ: ["1:15-1:40", "1:45-2:10", "2:15-2:40", "2:45-3:10"]
building_order: ["ABC", "XYZ"]
movement:
  policy: nonoverlap_time
  phase_slot:
    ABC: 1
    XYZ: 1
  min_buffer_minutes: 0
breaks: [2, 3]

areas: ["Energy", "Bio", "Theory"]
area_weights:
  Area1: 1.0
  Area2: 0.5

faculty_availability:
  Prof. A: [1, 2, 3, 4]
  Prof. B: [1, 2, 4]
  Prof. C: [1, 3, 4]
  Prof. D: [2, 3, 4]
  Prof. E: [1, 2, 3]
  Prof. F: [1, 3, 4]
